[2] - Добавили сервис для обращения к api валют
TestyTeam/multi-currency-control-app pull request #3
Opened 2023-01-06 09:38 UTC by KamilLatipov

2023-01-06 09:42 UTC, KamilLatipov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сервайс для получения данных по валютам](https://trello.com/c/ZAPbn1pu/2-%D1%81%D0%B5%D1%80%D0%B2%D0%B0%D0%B9%D1%81-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%BF%D0%BE-%D0%B2%D0%B0%D0%BB%D1%8E%D1%82%D0%B0%D0%BC)

2023-01-07 10:40 UTC, RuefulMage requested changes

2023-01-07 10:40 UTC, RuefulMage commented on src/services/api/currency.ts
> +const apiKey = '0Vr5mU6J4IgrU80wpHZoObFlxILssFvS';
Лучше вынести в environment

2023-01-07 10:40 UTC, RuefulMage commented on src/services/main-client.ts
> +          async (request, options, response) => {
Лучше вынести в отдельную функцию для лучшей читаемости кода

2023-01-14 16:58 UTC, KamilLatipov commented on src/services/main-client.ts
> +          async (request, options, response) => {
тут десять строка кода, не вижу смысла выносить в отдельную функцию
Если речь о том, чтобы вынести в функцию с selfrepresentative именем, то опять же не вижу сложности в понимании предназначения этих десяти строк

2023-01-14 16:58 UTC, KamilLatipov commented on src/services/api/currency.ts
> +const apiKey = '0Vr5mU6J4IgrU80wpHZoObFlxILssFvS';
Что такое environment ?

2023-01-14 18:18 UTC, RuefulMage approved these changes

2023-01-14 18:35 UTC, RuefulMage commented on webpack.config.js
> -    new ESLintPlugin({
Зачем?

2023-01-16 07:16 UTC, merged